// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
try {
  require('dotenv/config');
} catch {
  // dotenv not available in production - env vars set by container
}
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
